name: demo-onedata 
channels:
- conda-forge
dependencies:
- python
- xarray
- numpy
- scipy
- matplotlib
- cartopy
- xarray
- pip
- pip:
  - git+https://github.com/EGI-Foundation/egi-notebooks-addons
