name: demo-onedata 
channels:
- conda-forge
dependencies:
- python
- xarray
- numpy
- scipy
- matplotlib
- pip
- pip:
  - git+https://github.com/enolfc/egi-hub-addons
  - git+https://github.com/enolfc/fs-onedatafs@notebooks
  - git+https://github.com/onedata/onedatafs-jupyter
  - git+https://github.com/enolfc/onedatafs
